#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 17:26:33 2020

@author: hernando
"""
import NURBS as bs
import numpy as np

px=np.array([[1,2,3,4],[5,6,7,8,],[2,3,6,7]])
py=np.random.rand(3,4)
pz=np.random.rand(3,4)*px
w=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
p=2
q=2

u=np.linspace(0,1,40)
v=np.linspace(0,1,40)

cx=bs.NURBS2d(u,v,px,w,p,q)
cy=bs.NURBS2d(u,v,py,w,p,q)
cz=bs.NURBS2d(u,v,pz,w,p,q)
 

#bs.ploting3d(cx,cy,cz,'on',px,py,pz)

bs.plotingsurf(cx,cy,cz,px,py,pz)
