#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 18 19:07:52 2020

@author: hernando
"""
import numpy as np
import NURBS as bs

px=np.array([1,2,3,4,5,6,7,8,])
py=np.random.rand(8)
pz=np.random.rand(8)*px
w=np.array([1,1,1,1,10,1,1,1])
p=2

u=np.linspace(0,1,40)

cx=bs.NURBS(u,px,w,p)
cy=bs.NURBS(u,py,w,p)
cz=bs.NURBS(u,pz,w,p)
 

bs.ploting3d(cx,cy,cz,'on',px,py,pz)

