#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 18 18:16:56 2020

@author: hernando
"""
import numpy as np
import NURBS as bs


px=np.array([1,2,3,4,5,6,7,8,])
py=np.random.rand(8)
w=np.array([1,1,1,-0.1,1,1,1,1])
p=2

u=np.linspace(0,1,40)
cx=np.zeros(8)
cy=np.zeros(8)

cx=bs.NURBS(u,px,w,p)
cy=bs.NURBS(u,py,w,p)
 
bs.ploting2d(cx,cy)   
bs.ploting2d(px,py)   
#plt.plot(cx,cy)  
#plt.plot(px,py)     


